# Generated by Django 4.0.4 on 2022-05-20 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobintro', '0002_alter_apply_applycandidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='apply',
            unique_together={('applycandidate', 'appywork')},
        ),
    ]
